### ISSUE TITLE
PopularSoftwares列表太长，不方便查看

### ISSUE THREAD

**Issue by littleneko** [MintCN/Basics#3]
PopularSoftwares列表太长，虽然对，每种类型的软件分类了，但是还是很混乱，查看不是很方便。

**Comment by mudongliang** [comment]
这是一个问题。我最初的考虑是这个列表是一个比较丰富的列表库，然后我们在这个列表的基础之上构建很多不同的列表，比如说windows和linux平台软件对应列表。应该markdown的一些特性，让我们后面的工作比较好开展，比如，每一级的标题都会有一个对应的链接：邮件客户端（https://github.com/MintCN/Basics/blob/master/PopularSoftwares.md#%E9%82%AE%E4%BB%B6%E5%AE%A2%E6%88%B7%E7%AB%AF），Chrome（https://github.com/MintCN/Basics/blob/master/PopularSoftwares.md#chrome）等，如果你有什么好的意见，请提出来，大家一起讨论。

**Comment by mudongliang** [comment]
已经在文件初始位置加上目录。
